const Items = [
  {
    id: 1,
    mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682699543/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-1_rmh7lp.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682699543/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-1_rmh7lp.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682699548/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-2_p3chy5.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682699706/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-3_uhtwa6.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682699802/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-4_p404nm.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682700118/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-5_mksj57.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682700238/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-6_jfndeo.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682700374/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-7_uhh453.png",
    ],
    features: [
      "Home",
      "About",
      "Package",
      "Contact",
      "Blog",
      "A user can order through the Admin for Website services, Mobile Applications, Branding & Creative Content, as well as Internet Marketing & Advertising.",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "TailwindCSS",
      "React Leaflet",
      "React Hooks",
      "React icons",
      "Email JS",
      "Framer Motion",
    ],
    title: "MSN PRODUCTION",
    description:
      "PT. MULIA SEJATI NUSANTARA Established on June 24, 2019, a limited liability company engaged in supplier & contractor services. Then on January 22 2022 PT. MULIA SEJATI NUSANTARA Opening a new business branch in the Technology Sector which includes Website Creation, Mobile Applications, Branding, Creative Content, Digital Marketing & Advertising. This branch is called Mulia Sejati Nusantara Production or in short MSN PRODUCTION.",
    category: "business",
    liveLink: "https://msnproduction.com/",
    codeLink: "https://github.com/berthutapea/msnproduction.com",
  },
  {
    id: 2,
    mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682701479/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-4_kmaye9.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701456/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-1_jppjdj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701463/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-2_ptr4lg.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701467/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-3_gjle1m.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701479/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-4_kmaye9.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701489/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-5_nuhniv.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701492/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-6_rkvmhd.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701496/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-7_xjm4pm.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701499/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-8_dj0qoq.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701502/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-9_d1h5a0.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701505/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-10_kbbkd4.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701506/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-11_mmspfs.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Story searching and pagination",
      "CRUD operations (Story create, read, update and delete)",
      "Upload user ımages and story ımages to the server",
      "Liking stories and adding stories to the Reading list",
      "Commenting on the story",
      "Skeleton loading effect",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Asynsc Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Multer",
      "Slugify",
      "Cors",
    ],
    title: "MERN BLOG",
    description:
      "Fullstack open source blogging application made with MongoDB, Express, React & Nodejs (MERN)",
    category: "business",
    liveLink: "https://github.com/berthutapea/mern-blog-v2",
    codeLink: "https://github.com/berthutapea/mern-blog-v2",
  },
  {
    id: 3,
    mainImage: "https://i.ibb.co/bsFpVR1/super-bike-main.png",
    img: [
      "https://i.ibb.co/Jtdzytx/bike-1.png",
      "https://i.ibb.co/tQZBT1m/bike-2.png",
      "https://i.ibb.co/8mDkkYy/bike-3.png",
      "https://i.ibb.co/jftPgQp/bike-4.png",
    ],
    features: [
      "SignIn with email and password, google, facebook, github",
      "Secured Product Purchase Page",
      "Manage Product Warehouse",
      "Add a product to database",
      "Edit product details & update on database",
      "Remove a product from database",
      "Deliver a product",
      "Restock product",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React",
      "Firebase",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "JWT",
      "Heroku etc.",
    ],
    title: "Super Bike Warehouse",
    description:
      "A Warehouse website with warehouse management, product buying option, adding new products and many more features.",
    category: "business",
    liveLink: "https://super-bike-warehouse.web.app/",
    codeLink: "https://github.com/itsproali/super-bike-client",
  },
  {
    id: 4,
    mainImage: "https://i.ibb.co/c8ykxZv/learning-buddy-main.png",
    img: [
      "https://i.ibb.co/Twk9w2x/learning-buddy-1.png",
      "https://i.ibb.co/hVBxRV2/learning-buddy-2.png",
      "https://i.ibb.co/M5CT0Nj/learning-buddy-3.png",
    ],
    features: [
      "Enrolling In a Course Package",
      "Register a New User or Login a old User",
      "Social Media Sign In Option (Google & Facebook)",
      "Required Auth Private Route",
      "Learn More about Firebase/Authentication",
      "Know More about Me",
    ],
    technologies: [
      "React",
      "React Router",
      "React Tailwind",
      "Firebase Authentication",
      "React hot toast",
      "React Firebase Hooks",
    ],
    title: "Learning Buddy",
    description:
      "A website is created by focused on a tutor. He is selling his course package online. Where a user will be able to see the packages. If a user want to enroll to course, he/she need to login or register first. User can be logged in using email & password, Google, Facebook account. It is created with React.",
    category: "personal",
    liveLink: "https://learning-buddy-itsproali.web.app/",
    codeLink: "https://github.com/itsproali/learning-buddy",
  },
  {
    id: 5,
    mainImage: "https://i.ibb.co/r49F3pZ/convention-center-main.png",
    img: [
      "https://i.ibb.co/YhH7rZg/convention-center-1.png",
      "https://i.ibb.co/VjZLXzw/convention-center-2.png",
      "https://i.ibb.co/HH2X4wz/convention-center-3.png",
    ],
    features: [
      "Beautiful & minimalistic User Interface",
      "Banner Carousel with description",
      "Comparison with packages ",
      "Customer Reviews",
      "Navigation Menu",
    ],
    technologies: ["HTML", "CSS", "Bootstrap"],
    title: "Fantasy Convention  Center",
    description:
      "A simple & awesome looking convention center. They organize many types of events like, wedding, get-together, tour event, party or any other events.",
    category: "business",
    liveLink: "https://itsproali.github.io/fantasy-convention-center/",
    codeLink: "https://github.com/itsproali/fantasy-convention-center",
  },
];

export default Items;
